=== jovidel80/manageably-doc/schemas/project-list.schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "title": "Projects",
  "description": "A collection of projects.",
  "type": "array",
  "items": {
    "title": "Project",
    "description": "A specific project.",
    "type": "object",
    "properties": {
      "id": {
        "description": "Project ID.",
        "type": "number"
      },
      "name": {
        "description": "Project name.",
        "type": "string"
      },
      "startDate": {
        "type": "number"
      },
      "endDate": {
        "type": "number"
      }
    }
  }
}

=== jovidel80/manageably-doc/examples/project-list.example.json
[
  {
    "id": 1,
    "name": "Angular",
    "startDate": 1457558659,
    "endDate": 1457558659
  },
  {
    "id": 2,
    "name": "React",
    "startDate": 1457558659,
    "endDate": 1457558659
  },
  {
    "id": 3,
    "name": "Meteor",
    "startDate": 1457558659,
    "endDate": 1457558659
  }
]
